[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "requests>=2.32.3",
    "tweepy>=4.15.0",
    "twilio>=9.6.0",
]
